pywww/galleries/urls.py
from django.urls import path
from galleries.views import galleries, gallery_photos, add_gallery, add_gallery_photo

app_name = 'galleries'
urlpatterns = [
  path('', galleries, name='galleries'),
  path('add/', add_gallery, name='add_gallery'),
  path('<str:gallery_slug>/', gallery_photos, name='gallery_photos'),
  path('<str:gallery_slug>/add/', add_gallery_photo, name='add_gallery_photo'),
]

pywww/main/urls.py
from django.urls import path
from main.views import hello_world, about, contact, user_profile

app_name = 'main'
urlpatterns = [
    path('', hello_world, name='hello_world'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('user/<int:user_id>/profile/', user_profile, name='userprofile'),
]

pywww/pywww/urls.py
from django.conf import settings # needed to load static files
from django.conf.urls.static import static # needed to load static files
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('galleries/', include('galleries.urls')),
    path('posts/', include('posts.urls')),
    path('tags/', include('tags.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('main.urls')),
    path('', include('register.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # needed to load static files
    

pywww/galleries/models.py
import string
import random

from django.db import models
from django.utils.text import slugify
from common.models import Timestamp, SlugMixin

from sorl.thumbnail import ImageField
from tinymce import models as tinymce_models

# Create your models here.

# def get_random_text(n):
#   letters = string.ascii_letters
#   return ''.join(random.choice(letters) for i in range(n))

class Status(models.IntegerChoices):
  NEW = 1, 'new'
  HIDE = 2, 'hide'
  PUBLISHED = 3, 'published'

class Gallery(Timestamp, SlugMixin):
  class Meta:
    verbose_name = 'Galeria'
    verbose_name_plural = 'Galerie'
    # Zmiana nazw w PA
  
  title = models.CharField(max_length=100)
  # description = models.TextField(max_length=1500, blank=True, null=True)
  description =tinymce_models.HTMLField(blank=True, null=True)
  status = models.PositiveSmallIntegerField(default=Status.NEW, choices= Status.choices)
  # slug = models.SlugField(unique=True, max_length=150) [hide = 'hide', 'published', 'new']
  
  # @property
  # def photos_count(self):
  #   '''
  #   Pozwala na wyświetlenie dodatkowego pola w PA
  #   z informacją o ilości zdjęć
  #   '''
  #   return self.photos.count()
  
  def save(self, *args, **kwargs):
    '''
    Kiedy zapisujemy galerię ze statusem HIDE, 
    zdjęcia które do niej przynależą również otrzymują status HIDE
    '''
    if self.status == Status.HIDE:
      self.photos.update(status=Status.HIDE)
    super().save(*args, **kwargs)
  
  def __str__(self):
    return self.title
  
  # def save(self, *args, **kwargs):    # Zastąpione dziedziczenuiem z common
  #   if self._state.adding and not self.slug:
  #     slug = slugify(self.title)
  #     slugs = self.__class__.objects.values_list('slug', flat=True)
  #     if slugs:
  #       while True:
  #         if slug in slugs:
  #           slug += get_random_text(5)
  #         else:
  #           break
  #     self.slug = slug
  #   return super().save(*args, **kwargs)

def upload_to(instance, filename):
  return f'galleries/{instance.gallery.slug}/{filename}'
  
class Photo(Timestamp, SlugMixin):
  title = models.CharField(max_length=100)
  # slug = models.SlugField(unique=True, max_length=150)
  short_description = models.CharField(max_length=300, blank=True, null=True)
  image = ImageField(upload_to=upload_to)
  gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, related_name='photos')
  source = models.CharField(max_length=512, blank=True, null=True)
  status = models.PositiveSmallIntegerField(default=Status.NEW, choices=Status.choices)
  
  def __str__(self):
    return self.title 

pywww/galleries/forms.py
from django import forms

from .models import Gallery, Photo

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, ButtonHolder



class AddGalleryForm(forms.ModelForm):
  # status = forms.ChoiceField(
  #     ('NEW', 'new'),
  #     ('PUBLISHED', 'published'),
  #     ('HIDE', 'hide'),
  #   )
  
  class Meta:
    model = Gallery
    fields = ['title', 'description', 'status']
    labels = {
      'title': 'Tytuł',
      'description': 'Opis',
      'status': 'Status'
    }
    
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.helper = FormHelper()
    self.helper.form_method= 'POST'
    self.helper.layout = Layout(
      Fieldset(
        'Dodaj nową galerię',
        'title',
        'description',
        'status'
      ),
      ButtonHolder(
        Submit('submit', 'Zapisz', css_class='btn btn-primary'),
        css_class='d-flex justify-content-center'
      )     
    )
    
    
class AddGalleryPhotoForm(forms.ModelForm):

  class Meta:
    model = Photo
    fields = ['title', 'short_description', 'image', 'source', 'status']
    labels = {
      'title': 'Tytuł',
      'short_description': 'Opis',
      'image': 'Zdjęcie/Obraz',
      'source': 'Źródło',
      'status': 'Status'
    }
    
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.helper = FormHelper()
    self.helper.form_method= 'POST'
    self.helper.layout = Layout(
      Fieldset(
        'Dodaj zdjęcie do galerii',
        'title',
        'short_description',
        'image',
        'source',
        'status'
      ),
      ButtonHolder(
        Submit('submit', 'Dodaj', css_class='btn btn-primary'),
        css_class='d-flex justify-content-center'
      )     
    )

pywww/galleries/views.py
from multiprocessing import context
from django.shortcuts import render
from django.db.models import Avg, Min, Max, Count
from django.forms import modelformset_factory
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Gallery, Photo, Status
from .forms import AddGalleryForm, AddGalleryPhotoForm

# Create your views here.

def galleries(request):
  pub_photos = Photo.objects.filter(status=Status.PUBLISHED)
  # Zdjęcia o statusie PUBLISHED
  gall_id = pub_photos.values_list('gallery_id', flat=True).distinct()
  # Zwraca QuerySet zawierający id wszystkich galerii ze zdjęciami
  pub_gall_with_photos = Gallery.objects.filter(status=Status.PUBLISHED, id__in=gall_id)
  # Do template zostaną przekazane jedynie galerie ze statusem published
  '''
  pub_gall = Gallery.objects.filter(status=Status.PUBLISHED)
  # Galerie o statusie published
  pub_gall_with_photos = pub_gall.annotate(photos_count=Count('photos')).filter(photos_count__gt=0)
  # Galerie posiadające więcej niż jedno zdjęcie zastosownie annotacji
  '''
  context = {'pub_gall_with_photos': pub_gall_with_photos}
  return render(request, 'galleries/list.html', context)


def gallery_photos(request, gallery_slug):
  # Przekazuje zdjęcia z konkretnej galerii
  gallery = Gallery.objects.get(slug=gallery_slug)
  if gallery.status != Status.PUBLISHED:
    context = {'info': 'Galeria nie jest upubliczniona'}
  else:
    photos = Photo.objects.filter(gallery_id=gallery.id, status=Status.PUBLISHED)
    
    # Ilość elementów na stronie
    if request.method == 'POST':
      elem_on_page = int(request.POST.get('selected').strip('-'))
    # Elementy na stronie po wybraniu
    if request.method == 'GET':
      try:
        elem_on_page = int(request.GET.get('elem'))
      except:
        elem_on_page = 5
        # Ilość elementów na stronie domyślnie
        
    paginator = Paginator(photos, elem_on_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {'info': f'Galeria "{gallery.title}"',
               'gallery_slug': gallery_slug,
               'photos': photos,
               'page_obj': page_obj,
               'elem_on_page': elem_on_page}
  return render(request, 'galleries/gallery_photos.html', context)


def add_gallery(request):
  if request.method == 'POST' and request.user.is_authenticated:
    form = AddGalleryForm(request.POST)
    if form.is_valid():
      gallery = form.save()
      return HttpResponseRedirect(reverse('galleries:add_gallery_photo', args=[gallery.slug]))
  else:
    form = AddGalleryForm()
  return render(request, 'galleries/add_gallery.html', {'form': form})


def add_gallery_photo(request, gallery_slug):
  gallery = Gallery.objects.get(slug=gallery_slug)
  PhotosFormSet = modelformset_factory(Photo, form=AddGalleryPhotoForm, extra=1)
  # Tworzymy zbiór formularzy na podsatawie modelu Photo oraz formularzu AddGalleryPhotoForm (wyświetlanie jednego domyślnie)
  formset = PhotosFormSet(queryset=gallery.photos.none())
  # Formularze istniejących zdjęć nie będą zaliczane do formset
  if request.method == 'POST' and request.user.is_authenticated:
    formset = PhotosFormSet(request.POST, request.FILES)
    if formset.is_valid():
      print(formset)
      for f in formset.cleaned_data:
        if f:
          print(f)
          Photo.objects.create(gallery=gallery, **f)
    return HttpResponseRedirect(reverse('galleries:add_gallery_photo', args=[gallery_slug]))
  # if request.method == 'POST' and request.user.is_authenticated:
  #   form = AddGalleryPhotoForm(request.POST, request.FILES)
  #   if form.is_valid():
  #     form.save()
  #     info = 'Zdjęcie zostało dodane'
  #     form = AddGalleryPhotoForm()
  #     context = {'info': info, 'form': form}
  #     return render(request, 'galleries/add_gallery_photo.html', context)
  else:
    # form = AddGalleryPhotoForm()
    return render(request, 'galleries/add_gallery_photo.html', {'formset': formset})

pywww/galleries/templates/galleries/add_gallery copy.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block body %}

{% if user.is_authenticated %}
  {% crispy form %}
  {{ info }}

{% else %}
  <p class="mg-sm-top mg-sm-left">Zaloguj się by dodać nową galerię</p>

{% endif %}

{% endblock %}

pywww/galleries/templates/galleries/add_gallery.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block body %}

  <div class="col-md-6 offset-md-3">
    {% if user.is_authenticated %}
      {% crispy form %}
      {{ info }}
    {% else %}
      <p class="mg-sm-top mg-sm-left">Zaloguj się by dodać nową galerię</p>
    {% endif %}
  </div>

{% endblock %}


{% block script %}

  {{ gallery_form.media }}

{% endblock %}

pywww/galleries/templates/galleries/add_gallery_photo.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block body %}

{% if formset %}
  {% if user.is_authenticated %}
    <div class="col-6 offset-md-3">
      <form id="form-container" method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        <!-- {{ info }} -->
        {{ formset.management_form }}
        {% for form in formset %}
          <div class="photo-form mb-4">
            {{ form|crispy }}
            <hr>
          </div>
        {% endfor %}
        <button id="add-form" type="'button" class="btn btn-primary">Dodaj jeszcze jeden</button>
        <hr>
        <input type="submit" name="submit" value="Prześlij" class="btn btn-primary">
      </form>
    </div>
  {% else %}
    <p class="mg-sm-top mg-sm-left">Zaloguj się by dodać nowe zdjęcia do galerii</p>
  {% endif %}
{% endif %}

{% endblock %}

{%block script %}
  <script>
    let form = document.querySelectorAll(".photo-form")
    const container = document.querySelector("#form-container")
    const addButton = document.querySelector("#add-form")
    const totalForms = document.querySelectorAll("#id_form-TOTAL_FORMS")
    let formNum = form.length - 1
    addButton.addEventListener("click", addForm)
    function addForm(e) {
      e.preventDefault()
      let newForm = form[0].cloneNode(true)
      let formRegex = RegExp(`form-(\\d){1}-`, 'g')
      formNum++
      newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
      container.insertBefore(newForm, addButton)
      totalForms.setAttribute('value', `${formNum + 1}`)
    }
  </script>
{% endblock %}

pywww/galleries/templates/galleries/gallery_photos.html
{% extends 'base.html' %}

{% load static %}
{% load thumbnail %}

{% block style %}
  <link rel="stylesheet" href={% static "galleries/css/simple-lightbox.min.css" %}>
{% endblock %}

{% block title %}Galeria{% endblock %}

{% block body %}

  <div class="row my-2">
    <div class="col-sm">
      <h2 class="info mx-2" style="float: left;">{{ info }}</h2>
      <a href="{% url 'galleries:add_gallery_photo' gallery_slug %}">
        <span class="btn btn-secondary">Dodaj zdjęcia</span>
      </a>
    </div>
  </div>
  
  {# Wybór ilości elementów na stronie #}
  <form method="post">
    {% csrf_token %}
    <div class="form-row align-items-center mg-sm-left" style="display:flex;">
      <div class="col-auto my-1">
        <label class="mr-sm-2" for="inlineFormCustomSelect">Elementy na stronie</label>
        <select class="custom-select mr-sm-2" name="selected">
          <option selected>- {{ elem_on_page }} -</option>
          <option value="2">2</option>
          <option value="5">5</option>
          <option value="10">10</option>
          <option value="20">20</option>
        </select>
      </div>
      <div class="col-auto my-2">
        <button type="submit" class="btn btn-primary mg-sm-left">Zatwierdź</button>
      </div>
    </div>
  </form>

  {# Galeria wyświetlająca x zdjęć na stronie #}
    {% for photo in page_obj %}
      <div class="row mg-md-bott mg-sm-left">
        <div class="col-lg-4 col-sm-12" style="display:flex; justify-content: center">
          <!-- <img
            src="../media/{{ photo.image }}"
            class="w-100 shadow-1-strong rounded"
            style="max-width:300px"
            alt="{{photo.title}}"
            />  -->
            {% thumbnail photo.image '300' as im %}
            <div class="photo_gallery">
              <a href="{{ photo.image.url }}">
                <img src="{{ im.url }}" class="w-100 shadow-1-strong rounded" 
                style="max-width:300px" alt="{{ photo.title }}">
              </a>
            </div>
            {% endthumbnail %}
          </div>
          <div class="col-lg-8 col-sm-12">
            <h3>{{photo.title|capfirst}}</h3>
            <p>Opis:<br>
              {% if photo.short_description %}
              {{photo.short_description}}
            {% else %}
            Brak opisu
            {% endif %}
          </p>
        </div>
      </div>
    {% endfor %}

  {# Obsługa paginacji #}
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}&elem={{ elem_on_page }}">&laquo; Poprzednia</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1" aria-disabled="True">&laquo; Poprzednia</a>
        </li>
      {% endif %}

      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active" aria-current="page">
            <span class="page-link">
              {{ i }}
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}&elem={{ elem_on_page }}" >{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}&elem={{ elem_on_page }}">Następna &raquo;</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Następna &raquo;</a>
      </li>
      {% endif %}
    </ul>
  </nav>

{% endblock %}

{%block script %}
  <script src={% static "galleries/js/simple-lightbox.min.js" %}></script>         
  <script>
    var gallery = new SimpleLightbox('.photo_gallery a');
  </script>
{% endblock %}

pywww/galleries/templates/galleries/list.html
{% extends 'base.html' %}

{% load static %}
{% load thumbnail %}

{% block title %}Galerie{% endblock %}

{% block body %}

  <div class="col-sm m-3">
    <h2 class="info ">Lista opublikowanych galerii:</h2>
  </div>
  
  <div class="row ms-4">
    {% for gallery in pub_gall_with_photos %}
    <div class="col-lg-2 col-md-3 col-sm-6 mb-4">
      <div class="card h-100">
        {% thumbnail gallery.photos.first.image '150x150' crop='center' as im %}
        <img src="{{ im.url }}" alt="{{ gallery.title }}" class="card-img-top">
        {% endthumbnail %}
        <div class="card-body">
          <h4 class="card-title text-center">{{ gallery.title }}</h4>
        </div>
        <div class="card-footer text-center">
          <a class='btn btn-primary' href='{{ gallery.slug }}'>Pokaż</a> 
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  
  <div class="m-3">
    <a href="{% url 'galleries:add_gallery' %}">
      <span class="btn btn-secondary">Dodaj galerię</span>
    </a>
  </div>

  {% endblock %}