pywww/books/urls.py
from django.urls import path
from books.views import books_list, books_table, details, add_book_form, edit_book_form, handle_book_borrows

app_name = 'books'
urlpatterns = [
    path('', books_list, name='list'),
    path('add/', add_book_form, name='add'),
    path('table/', books_table, name='table'),
    path('<int:book_id>/borrows/', handle_book_borrows, name='borrows'),
    path('borrows-list/', handle_book_borrows, name='borrows_list'),
    path('<int:book_id>/edit/', edit_book_form, name='edit'),
    path('<int:book_id>/', details, name='details'),
]

pywww/main/urls.py
from django.urls import path
from main.views import hello_world, about, contact, user_profile

app_name = 'main'
urlpatterns = [
    path('', hello_world, name='hello_world'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('user/<int:user_id>/profile/', user_profile, name='userprofile'),
]

pywww/pywww/urls.py
from django.conf import settings # needed to load static files
from django.conf.urls.static import static # needed to load static files
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('galleries/', include('galleries.urls')),
    path('posts/', include('posts.urls')),
    path('tags/', include('tags.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('main.urls')),
    path('', include('register.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # needed to load static files
    

pywww/books/models.py
from django.db import models
from common.models import Timestamp

from sorl.thumbnail import ImageField

# Create your models here.
class Author(Timestamp):
  class Meta:
    verbose_name = "Autor"
    verbose_name_plural = "Autorzy"
    # Zmiana wyświetlania nazwy w PA
  
  name = models.CharField(max_length=200)
  birth_year = models.IntegerField()
  death_year = models.IntegerField(blank=True, null=True)
  # blank=True pole może zostać pominięte(puste), null=True dopuszczamy by komórka miała wartość NULL
  biogram = models.TextField(blank=True)
  
  def __str__(self):
    if self.birth_year and self.death_year:
      return f"{self.name} ({self.birth_year} - {self.death_year})"
    return f"{self.name}"


class Book(Timestamp):
  class Meta:
    verbose_name = "Książka"
    verbose_name_plural = "Książki"
    
  title = models.CharField(max_length=255)
  # tytuł książki z ograniczeniem znaków
  description = models.TextField(max_length=1500)
  # opis książki z ograniczeniem znaków
  available = models.BooleanField(default=True)
  # flaga true/false
  publication_year = models.SmallIntegerField(help_text="Please use this format 'YYYY'", blank=True, null=True)
  # rok publikacji, może być pusty
  authors = models.ManyToManyField(Author, related_name="books")
  # autor książki - możliwe wielu autorów
  tags = models.ManyToManyField("tags.Tag", blank=True, related_name="books")
  # Dodanie do książek tagów w relacji M2M oraz umożliwienia wyszukiwania książek po tagu dzięki related_name
  image = ImageField(upload_to='books/covers/%Y/%m/%d', blank=True, null=True)
  # możliwość dodania obrazu do pliku, plik nie jest wymagany w formularzu (blank=True) oraz nie jest wymagany w BD (null=False)
  
  def __str__(self):
    # metoda specjalna służąca do przygotowania reprezentacji
    # tekstowej naszego obiektu. Zmiana w widoku jak i w PA
    return f"{self.id}. {self.title}"
  
  
class Borrow(models.Model):
  book = models.ForeignKey('Book', on_delete=models.CASCADE, related_name='borrows')
  #related_name Nazwa używana do relacji z powiązanego obiektu do tego (z Book do Borrow)
  user = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='borrows')
  borrow_date = models.DateTimeField(auto_now_add=True)
  return_date = models.DateTimeField(blank=True, null=True)
  

  
  

pywww/books/forms.py
from pyexpat import model
from django import forms

from books.models import Book, Author
from tags.models import Tag

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, ButtonHolder

from django.contrib import admin
from django.contrib.admin.widgets import AutocompleteSelectMultiple
from dal import autocomplete


'''
class BookForm(forms.ModelForm):
  tags = forms.ModelMultipleChoiceField(
    # Możliwość wyszukiwania tagów i przypisywania ich poza PA
        queryset=Tag.objects.all(),
        # widget=AutocompleteSelectMultiple(
        #   Book._meta.get_field('tags'),
        #   admin.AdminSite()
        # ) Do wyszukiwania tagów bez korzystania z DAL
        widget=autocomplete.ModelSelect2Multiple(url='tags:tag-autocomplete'),
  )
  
  class Meta:
    model = Book
    fields = ('title',
              'description',
              'available',
              'publication_year',
              'authors',
              'tags',
              'image')

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.helper = FormHelper()
    self.helper.form_method = 'post'
    self.helper.form_action = ''
    self.helper.layout = Layout(
      Fieldset(
        'Add Book',
        'title',
        'authors',
        'publication_year',
        'description', 
        'available',
        'tags',
        'image'
      ),
      ButtonHolder(
        Submit('submit', 'Dodaj', css_class='btn btn-primary'),
        css_class='d-flex justify-content-center'
      )
    )
'''  
  
class BookBorrowForm(forms.Form):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.helper = FormHelper()
    self.helper.form_method = 'post'
    self.helper.add_input(Submit('borrow', 'Wypożycz'))
    
    
class AuthorForm(forms.ModelForm):
  class Meta:
    model = Author
    fields = '__all__'
    
     
class BookForm(forms.ModelForm):
  
  tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=autocomplete.ModelSelect2Multiple(url='tags:tag-autocomplete')
        )
  authors = forms.ModelMultipleChoiceField(
        queryset=Author.objects.all(),
        required=False
        )
  class Meta:
    model = Book
    fields = '__all__'

pywww/books/views.py
# from django.shortcuts import render -deleted
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.forms import modelformset_factory
from django.urls import reverse
from django.utils import timezone

from books.models import Author, Book, Borrow
from books.forms import AuthorForm, BookForm, BookBorrowForm


# Create your views here.
def books_list(request):
  all_books = Book.objects.all()
  books = Book.objects
  context = {'books': all_books, 'unavilable_books': books.filter(available="0"), 'avilable_books': books.filter(available="1")}
  return render(request, 'books/store.html', context)


def books_table(request):
  books = Book.objects.all()
  context = {'books': books}
  return render(request, 'books/books_table.html', context)


def details(request, book_id):
  book = Book.objects.get(id=book_id)
  form = BookBorrowForm()
  form.helper.form_action = reverse('books:borrows', args=[book.id])
  context = {
            'book': book,
            'form': form
             }
  return render(request, 'books/details.html', context)


def add_book_form(request):
  form = BookForm()
  AuthorFormSet = modelformset_factory(Author, form=AuthorForm)
  formset = AuthorFormSet(queryset=Author.objects.none())
  if request.method == 'POST' and request.user.is_authenticated:
    form = BookForm(request.POST, request.FILES)
    formset = AuthorFormSet(request.POST)
    if form.is_valid():
      instance = form.save()
      if formset.is_valid():
        for f in formset.cleaned_data:
          if f:
            author, _ = Author.objects.get_or_create(**f)
            if author not in instance.authors.all():
              # Coś tu nie trybi. I tak dodaje nowego identycznego autora
              instance.authors.add(author)
        instance.save()
    return HttpResponseRedirect(reverse('books:add'))
  return render(request,
                'books/add_book.html',
                {'form': form, 'formset': formset}
              )
    # form = BookForm(request.POST, request.FILES)
    # if form.is_valid():
    #   form.save()
    #   form.save_m2m()
    #   # Zapis elementów powiązanych m2m z book
    #   return HttpResponseRedirect(reverse('books:add'))
  #   form = BookForm()
  # return render(request, 'books/add_book.html', {'form': form})


def edit_book_form(request, book_id):
  book = get_object_or_404(Book, id=book_id)
  if request.method == 'POST' and request.user.is_authenticated:
    form = BookForm(request.POST, request.FILES, instance=book)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect(reverse('books:details', args=[book_id]))
  else:
    form = BookForm(instance=book)
      
  return render(request, 'books/add_book.html', {'form': form})


def handle_book_borrows(request, book_id=None):
  # Po wejściu z details
  user = request.user
  if user.is_authenticated:
    if request.method == 'POST':
    # Po kliknięciu wypożycz w details
      if request.POST.get('borrow'):
        book = Book.objects.get(pk=book_id)
        Borrow.objects.create(
          user = user, 
          book = book
        )
        book.available = False
        book.save()
        return HttpResponseRedirect(reverse('books:details', args=[book_id]))
      else:
        keys = [key for key in request.POST.keys() if key.startswith('book_')]
        key = int(keys[0].split('_')[1])
        book = Book.objects.get(id=key)
        borrow = Borrow.objects.filter(user=user, book=book).last()
        # Ostatnia z wypożyczonych książek
        if not borrow.return_date:
          borrow.return_date = timezone.now()
          borrow.save()
          book.available = True
          book.save()
        return HttpResponseRedirect(reverse('books:borrows_list'))     
    else:
      borrows = Borrow.objects.filter(user=user)
      return render(request, 'books/borrows_list.html', {'borrows': borrows})
  else:
     return HttpResponseRedirect(reverse('books:list'))   
    

pywww/books/templates/books/add_book.html
{% extends "books/layout.html" %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %}Add book to library{% endblock %}

{% block style %}
  <style>
    .form-control {
      background-color: rgb(240, 239, 226);
    }

    .btn{
      background-color: rgb(100, 181, 228);
    }

    .btn:hover{
      background-color: rgb(76, 136, 172);;
    }
  </style>  
{% endblock %}


{% block body %}

  {% if formset %}
    <div class="col-md-6 offset-md-3">
      <form id="form-container" action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h4>Dodaj książkę</h4>
        {{ form|crispy }}
        <hr>
        {{ formset.management_form }}
        <h4>Dodaj autora książki</h4>
        {% for form in formset %}
          <div class="book-form mb-4">
            {{ form|crispy }}
            <hr>
          </div>
        {% endfor %}
        <button id="add-form" type="button" class="btn btn-priamry">Dodaj kolejnego autora</button>
        <hr>
        <input type="submit" name="submit" value="Prześlij" class="btn">
      </form>
    </div>
  {% endif %}

{% endblock %}


{% block script %}
  <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
  {{ form.media }} <!-- Do tagów -->
  <script>
    let form = document.querySelectorAll(".book-form")
    const container = document.querySelector("#form-container")
    const addButton = document.querySelector("#add-form")
    const totalForms = document.querySelectorAll("#id_form-TOTAL_FORMS")
    let formNum = form.length - 1
    addButton.addEventListener("click", addForm)
    function addForm(e) {
      e.preventDefault()
      let newForm = form[0].cloneNode(true)
      let formRegex = RegExp(`form-(\\d){1}-`, 'g')
      formNum++
      newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
      container.insertBefore(newForm, addButton)
      totalForms.setAttribute('value', `${formNum + 1}`)
    }
  </script>
{% endblock %}

pywww/books/templates/books/books_table.html
{% extends "books/layout.html" %}

{% block title %}Table of books{% endblock %}

{% block style %}
  <style>
    .container {
      margin: 1rem;
      padding-left: 1rem;
    }

    table, th, td {
      border: 1px solid;
      border-collapse: collapse;
      border-color: black;
    }

    th {
      min-width: 15vw;
    }

    .table__header-id {
      min-width: 40px;
    }

    .table__row--marked:hover {
      background-color: rgb(99, 99, 99);
      color: rgb(255, 255, 255);
    }

    .table__column--id {
      text-align: center;
    }

    .table__column--author {
      padding-right: 1rem; 
    }

    a {
      text-decoration: none;
      color: inherit;
    }

    a:hover {
      font-weight: bold;
      color: #eeeeee;
    }

  </style>
{% endblock %}


{% block body %}
<div class="container">
  <h1>Books in our library</h1>
  <br>
  <h2>Table</h2>
  <table>
    <tr>
      <th class="table__header-id">Id</th>
      <th>Title</th>
      <th>Author</th>
      <th>Publication year</th>
      <th>Availability</th>
    </tr>
    {% for book in books %}
        <tr class="table__row--marked">
            <td class="table__column--id">{{ book.id }}</td>
            <td class="table__column--title">
              <a href="{% url 'books:details' book.id %}">{{ book.title }}</a>
            </td>
            <td class="table__column--author">
              {% for author in book.authors.all %}
                {% if author == book.authors.all.last %}
                  {{ author.name }}
                {% else %}
                  {{ author.name }}, 
                {% endif %}
              {% endfor %}
            </td>
            <td>{{ book.publication_year }}</td>
            {% if book.available == True %}
              <td>On the shelf</td>
            {% else %}
              <td>Lended out</td>
            {% endif %}
        </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

pywww/books/templates/books/borrows_list.html
{% extends "books/layout.html" %}

{% block title %}Lista wypożyczonych książek{% endblock %}

{% block body %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Numer</th>
      <th scope="col">Tytuł</th>
      <th scope="col">Data wypożyczenia</th>
      <th scope="col">Data zwrotu</th>
    </tr>
  </thead>
  <tbody>
    {% for borrow in borrows %}
      <form action="{% url 'books:borrows_list' %}" method="post">
      {% csrf_token %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ borrow.book.title }}</td>
        <td>{{ borrow.borrow_date }}</td>
        <td>
          {% if borrow.return_date %}
            {{ borrow.return_date }}
          {% else %}
            <button type="submit" name="book_{{ borrow.book.id }}" class="btn btn-primary">Zwróć</button>
          {% endif %}
        </td>
      </tr>
      </form>
    {% endfor %}
  </tbody>
</table
{% endblock %}

pywww/books/templates/books/details.html
{% extends "books/layout.html" %}

{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}Book's details{% endblock %}

{% block style %}
  <style>
    .container {
      margin: 1rem;
      padding-left: 1rem;
    }
    .book__details {
      list-style: none;
      margin: 0.5rem;
    }
    .book__details--detail {
      padding: 0.5rem;
    }

    .book__header {
      display: flex;
      align-items: center;
    }

    .book__header--img {
      width: 100px;
      height: auto;
      margin-left: 4rem;
    }
  </style>
{% endblock %}


{% block body %}
  <div class="container">
    <div class="book__header">
      <h1 class="book__header--title">
        {{ book.id }}.
        {{ book.title }}
      </h1>
      {% if book.image %}
        {% thumbnail book.image "200x290" as im %} <!-- zmiana rozdzielczości (miniaturki) -->
          <img class="book__header--img" src="{{ im.url }}">
        {% endthumbnail %}
        <!-- <img class="book__header--img" src="{{ book.image.url }}" alt="cover"> -->
      {% endif %}
    </div>
    <h2 class="book__details">Details:</h2>
    <ul class="book__details">
      <li class="book__details--detail">Author: <br>
        {% for author in book.authors.all %}
          {% if forloop.last %}
            {{ author.name }}
          {% else %}
            {{ author.name }}, 
          {% endif %}
        {% endfor %}
      </li>
      <li class="book__details--detail">Publication Year: <br>{{ book.publication_year }}</li>
      <li class="book__details--detail">Description: <br>{{ book.description }}</li>
      <li class="book__details--detail">Availability: <br>
        {% if book.available == True %}
          Available
        {% else %}
          Unavailable
        {% endif %}
      </li>
    </ul>
    {% if user.is_authenticated %}
      {% if book.available == True %}
        {% crispy form %}
      {% endif %}
      <br>
      <p><a href="{% url 'books:edit' book_id=book.id %}">Edit this book</a></p>
    {% endif %}
  </div>
{% endblock %}

pywww/books/templates/books/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href={% static "books/css/style.css" %}>
    {% block style %}{% endblock %}

    <title>{% block title %}{% endblock %}</title>
  </head>

  <body>
    <header class="header">
      <h2 class="header__title">Old Bookstore</h2>
      <ul class="header__nav">
        <li class="nav__page">
          <a href="{% url 'books:list' %}">List of books</a>
        </li>
        <li class="nav__page">
          <a href="{% url 'books:table' %}">Main table</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav__page">
            <a href="{% url 'books:add' %}">Add book</a>
          </li>
          <li class="nav__page">
            <a href="{% url 'books:borrows_list' %}">Borrowed books</a>
          </li>
        {% endif %}
        <li class="nav__page">
          <img class="header__title-img" src={% static "books/img/title-books.png" %} alt="Logo">
        </li>
      </ul>
    </header>

    {% block body %}{% endblock %}

  </body>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  {%block script %}{% endblock %}

</html>

pywww/books/templates/books/store.html
{% extends "books/layout.html" %}

{% block style %}
  <style>

    .container, p {
      margin: 1rem;
      padding-left: 1rem;
    }
  </style>
{% endblock %}

{% block body %}
  <div class="container">
    <h1>Lista książek:</h1>
    <ul>
      {% for book in books %}
        <li>{{book.title}}</li>
      {% endfor %}
    </ul>

    <p>Książki dostępne:</p>
    <ol>
      {% for avilable_book in avilable_books %}
        <li>{{avilable_book.title}}</li>
      {% endfor %}
    </ol>
    
    <p>Książki niedostępne:</p>
    <ol>
      {% for unavilable_book in unavilable_books %}
        <li>{{unavilable_book.title}}</li>
      {% endfor %}
    </ol>
    <p>Chwilowy brak nakładu</p>
  </div>
    
{% endblock %}