pywww/books/urls.py
from django.urls import path
from books.views import books_list, books_table, details, add_book_form, edit_book_form, handle_book_borrows

app_name = 'books'
urlpatterns = [
    path('', books_list, name='list'),
    path('add/', add_book_form, name='add'),
    path('table/', books_table, name='table'),
    path('<int:book_id>/borrows/', handle_book_borrows, name='borrows'),
    path('borrows-list/', handle_book_borrows, name='borrows_list'),
    path('<int:book_id>/edit/', edit_book_form, name='edit'),
    path('<int:book_id>/', details, name='details'),
]

pywww/galleries/urls.py
from django.urls import path
from galleries.views import galleries, gallery_photos, add_gallery, add_gallery_photo

app_name = 'galleries'
urlpatterns = [
  path('', galleries, name='galleries'),
  path('add/', add_gallery, name='add_gallery'),
  path('<str:gallery_slug>/', gallery_photos, name='gallery_photos'),
  path('<str:gallery_slug>/add/', add_gallery_photo, name='add_gallery_photo'),
]

pywww/main/urls.py
from django.urls import path
from main.views import hello_world, about, contact, user_profile

app_name = 'main'
urlpatterns = [
    path('', hello_world, name='hello_world'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('user/<int:user_id>/profile/', user_profile, name='userprofile'),
]

pywww/posts/urls.py
from django.urls import path
# from django.conf.urls.static import static
from posts.views import posts_list, post_details, add_post_form, edit_post, listing


app_name = 'posts'
urlpatterns = [
    path('', posts_list, name='list'),
    path('plist/', listing, name='plist'), # Lista po paginacji
    # path('add', add_post, name='add'),
    # path('add', add_post_form, name='add'), -->with PostForm(forms.Form):
    path('add/', add_post_form, name='add'),
    path('<int:post_id>/edit/', edit_post, name='edit'),
    path('<int:post_id>/', post_details, name='post_details'),
]

pywww/pywww/urls.py
from django.conf import settings # needed to load static files
from django.conf.urls.static import static # needed to load static files
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('galleries/', include('galleries.urls')),
    path('posts/', include('posts.urls')),
    path('tags/', include('tags.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('main.urls')),
    path('', include('register.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # needed to load static files
    

pywww/register/urls.py
from django.urls import path

from .views import register 

app_name = 'register'
urlpatterns = [
  path('register/', register, name='register'),
]

pywww/templates/base.html
{% load static %} <!-- settings.py INSTALLED_APPS= [django.contrib.staticfiles] -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link href={% static "main/css/style.css" %} rel="stylesheet">
  {% block style %}{% endblock %}

  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'main:hello_world' %}">
      <img class="img--logo" src={% static "main/img/logo.png" %} alt="Logo">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav" style="width: 100%; justify-content: space-between">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{% url 'main:hello_world' %}">Strona główna</a>
          <a class="nav-item nav-link" href="{% url 'posts:list' %}">Lista postów</a>
          <a class="nav-item nav-link" href="{% url 'books:list' %}">Lista książek</a>
          <a class="nav-item nav-link" href="{% url 'galleries:galleries' %}">Galerie</a>
        </div>
        <div>
          {% if user.is_authenticated %}
            <a type="button" class="btn btn-outline-primary me-2" href="{% url 'logout' %}">Logout</a>
          {% else %}
            <a type="button" class="btn btn-outline-priamry me-2" href="{% url 'login' %}">Login</a>
            <a type="button" class="btn btn-primary" href="{% url 'register:register' %}">Sign-up</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>

  <!-- <header>
    <img class="img--logo" src={% static "main/img/logo.png" %} alt="Logo">
    To jest header
  </header> -->

  <!-- <nav>
    <ul>
      <li>
        <a href="{% url 'main:hello_world' %}">Strona główna</a>app_name:name -->
      <!-- </li>
      <li>
        <a href="{% url 'posts:list' %}">Lista postów</a>
      </li>
    </ul> -->

    <!-- <div class="col-md-3 text-end">
      {% if user.is_authenticated %}
        <a type="button" class="btn btn-outline-primary me-2" href="{% url 'logout' %}">Logout</a>
      {% else %}
        <a type="button" class="btn btn-outline-priamry me-2" href="{% url 'login' %}">Login</a>
        <a type="button" class="btn btn-primary" href="{% url 'register:register' %}">Sign-up</a>
      {% endif %}
    </div>
  </nav>
     -->
      
  {% block body %}{% endblock %}

  <footer>
    <nav>
      <ul>
        <li>
          <a href="{% url 'main:about' %}">O projekcie</a><!-- app_name:name -->
        </li>
      </ul>
    </nav>
  </footer>

</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
{%block script %}{% endblock %}

</html>